# This is a simple example of using a config map to create a single page static site.
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "kubernetespoc.fullname" . }}
  namespace: {{ .Values.namespace }}
{{- if .Values.configMaps }}
data:
  appSettings:
  {{- if .Values.configMaps.appSettings.connectionStrings }}  
    connectionStrings: 
  {{- range $key, $val := .Values.configMaps.appSettings.connectionStrings }}
      {{ $key }}: {{ $val }}    
  {{- end }}
  {{- end }}
{{- end }}