# This is a simple example of using a config map to create a single page static site.
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kubernetespoc.fullname" . }}
  namespace: {{ .Values.namespace }}
type: Opaque
{{- if .Values.secrets }}
data:
{{- range $key, $val := .Values.configMaps.appSettings.connectionStrings }}
  {{ $key }}: {{ $val }}
{{- end }}
{{- end }}